#!/bin/bash

mpBin="$HOME/Programs/MadPascal/mp"
mpBase="$HOME/Programs/MadPascal/base"
madsBin="$HOME/Programs/mads/mads"
name="suite"

$mpBin ${name}.pas -o

if [ -f ${name}.a65 ]; then
  [ ! -d "output" ] && mkdir output
  mv ${name}.a65 output/
  cd output
  $madsBin ${name}.a65 -x -i:$mpBase -o:${name}.xex
  cd ..
else
  exit 1
fi
