//---------------------------

yoshplus.run;
printScore(yoshplus.name, 0);

//---------------------------

sieve.run;
printScore(sieve.name, 1);

//---------------------------

bsort.run;
printScore(bsort.name, 2);

//---------------------------

countdown_for.run;
printScore(countdown_for.name, 3);

//---------------------------

countdown_while.run;
printScore(countdown_while.name, 4);

//---------------------------

montecarlo.run;
printScore(montecarlo.name, 5);

//---------------------------

chessboard.run;
printScore(chessboard.name, 6);

//---------------------------
